version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "80:80"
      - "2222:22"
    volumes:
      - ./images:/var/www/html/images
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    container_name: nginx_server