---
- name: Update SSH configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart SSH

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted